### PR TITLE
Bump version to 2.0

### PR DESCRIPTION
**Pull request by jeffaburt**
This bumps the version to 2.0, which supports Swift 3. 

After merging this PR, please create a 2.0 tag:

```
cd Pluralize.swift/
git checkout master
git pull origin master
git tag 2.0
git push origin 2.0
```

Then, send an update to CocoaPods, that way we can just run `pod update Pluralize.swift` and get all of the Swift 4 goodies:

```
pod trunk push
```

Thanks a lot!

### CODE REVIEW

**Comment by DavidLari** [comment]
FYI: This repo seems to be abandoned. The author has not responded to any pulls or issues in almost a year. In fact, he's not been active in Github at all since January.

**Comment by jeffaburt** [comment]
Thanks for the heads up. That's too bad, really.

**Comment by jeffaburt** [comment]
@joshualat do you mind cutting a release? Good news: no code changes are needed to support Swift 4 as https://github.com/joshualat/Pluralize.swift/commit/45ec1ca1094293b4985934d8df57150fe2d417aa compiles with no errors! I'd love to not have to reference the commit in my `Podfile`. Thanks!

**Comment by DavidLari** [comment]
Joshua still has no Github activity since January. :(

**Pull request closed without merging**
